# From mocha https://catppuccin.com/palette
[palette]
    rosewater = "#f5e0dc"
	flamingo = "#f2cdcd"
	pink = "#f5c2e7"
	mauve = "#cba6f7"
	red = "#f38ba8"
	maroon = "#eba0ac"
	peach = "#fab387"
	yellow = "#f9e2af"
	green = "#a6e3a1"
	teal = "#94e2d5"
	sky = "#89dceb"
	sapphire = "#74c7ec"
	blue = "#89b4fa"
	lavender = "#b4befe"
	text = "#cdd6f4"
	subtext1 = "#bac2de"
	subtext0 = "#a6adc8"
	overlay2 = "#9399b2"
	overlay1 = "#7f849c"
	overlay0 = "#6c7086"
	surface2 = "#585b70"
	surface1 = "#45475a"
	surface0 = "#313244"
	base = "#1e1e2e"
	mantle = "#181825"
	crust = "#11111b"

# Latte colours
    dark_red = "#d20f39"
    dark_green = "#40a02b"
    dark_yellow = "#df8e1d"
    dark_blue = "#1e66f5"

[options]
    winborder = "rounded"

[group.Normal]
    fg = "p:text"

[group.Cursor]
    fg = "p:mantle"
    bg = "p:text"
    bold = true

[group.ErrorMsg]
    fg = "p:red"
    bold = true
    italic = true

[group.WarnMsg]
    fg = "p:peach"
    bold = true
    italic = true

[group.ModeNormal]
    fg = "p:mantle"
    bg = "p:blue"
    bold = true

[group.ModeCommand]
    fg = "p:mantle"
    bg = "p:peach"
    bold = true

[group.ModeInsert]
    fg = "p:mantle"
    bg = "p:green"
    bold = true

[group.FloatBoarder]
    fg = "p:blue"

[group.FloatBoarderNC]
    fg = "p:subtext0"

[group.FloatTitle]
    link = "FloatBoarder"

[group.FloatTitleNC]
    link = "FloatBoarderNC"

[group.FileTreeDir]
    fg = "p:blue"

[group.FileTreeWindow]
    fg = "p:yellow"

[group.PianoRollNote]
    fg = "p:mantle"
    bg = "p:green"
    bold = true
    italic = true

[group.PianoRollNoteAccent]
    fg = "p:dark_green"
    bg = "p:green"

[group.PianoRollWhiteKey]
    fg = "p:mantle"
    bg = "p:text"
    bold = true
    italic = true

[group.PianoRollBlackKey]
    fg = "p:text"
    bg = "p:surface0"
    bold = true
    italic = true

[group.PianoRollWhiteKeyPressed]
    fg = "p:mantle"
    bg = "p:peach"
    bold = true
    italic = true

[group.PianoRollBlackKeyPressed]
    link = "PianoRollWhiteKeyPressed"

[group.PainoRollBarSeparator]
    fg = "p:surface2"

[group.PainoRollBeatSeparator]
    link = "PainoRollBarSeparator"

[group.PainoRollSubDivSeparator]
    fg = "p:surface0"
